### ISSUE TITLE
WYSIWYG 组件的 z-index 应大于 O2M 弹出窗口

### ISSUE THREAD

**Issue by everyx** [fengsi-io/directus-v8#1]
![bug](https://user-images.githubusercontent.com/1665522/100683471-5ef1ce80-33b3-11eb-8803-27d584307ba2.gif)

**Comment by wusongliang** [comment]
![image](https://user-images.githubusercontent.com/51825134/100695312-e4817880-33cb-11eb-8648-1c5d8fd9c287.png)

**Comment by wusongliang** [comment]
本地的没有问题
