### ISSUE TITLE
富文本支持表格

### ISSUE THREAD

**Issue by wusongliang** [fengsi-io/directus-v8#48]

**Comment by wusongliang** [comment]
是这里的表格吗？他好像已经有的
![image](https://user-images.githubusercontent.com/51825134/105688968-2b579e80-5f35-11eb-8496-7f71d6955459.png)
![image](https://user-images.githubusercontent.com/51825134/105689046-40ccc880-5f35-11eb-9016-96abec6c158b.png)

**Comment by everyx** [comment]
是的，那就关闭这个问题吧。
